In [1]:
import pandas as pd

In [2]:
data_file = "windows_store_top15_data.csv"

data_df = pd.read_csv(data_file)

data_df

Name     Price  \
0                   WhatsApp Desktop      Free   
1                   Telegram Desktop      Free   
2     Amazon Prime Video for Windows      Free   
3                          Instagram      Free   
4                      Spotify Music      Free   
...                              ...       ...   
3892           Vegas Slots Machine *  ₹ 109.00   
3893              Crossword Puzzle +  ₹ 109.00   
3894                     Rescue Team  ₹ 219.00   
3895                  Doodle Kingdom   ₹ 29.00   
3896                    Doodle Devil   ₹ 29.00   

                                            Description  \
0     With WhatsApp on the desktop, you can seamless...   
1     Pure instant messaging — simple, fast, secure,...   
2     Watch movies and TV shows recommended for you,...   
3     Bringing you closer to the people and things y...   
4     Love music? Play your favorite songs and album...   
...                                                 ...   
3892  Windows version Vegas style slot machine casin...   
3893  Crossword Puzzle is a casual crossword and cro...   
3894  Mother Nature has done a number on an island p...   
3895  It's time to get MEDIEVAL!\r\n\r\nFrom the cre...   
3896  Great Halloween Sale! 50% off all in-app purch...   

                                   Publisher Date of Release       Category  \
0                              WhatsApp Inc.          1/2/17         Social   
1                     Telegram Messenger LLP          3/4/17         Social   
2     Amazon Development Centre (London) Ltd      24-02-2020  Entertainment   
3                                  Instagram      26-02-2016         Social   
4                                 Spotify AB      26-05-2017  Entertainment   
...                                      ...             ...            ...   
3892                               Cool Inc.      30-01-2018          Games   
3893                                App Best      30-01-2018          Games   
3894               Alawar Entertainment Inc.      29-05-2013          Games   
3895                             JoyBits Ltd      25-11-2013          Games   
3896                             JoyBits Ltd      24-09-2012          Games   

           Size          Age Rating  \
0     379.39 MB   For ages 3 and up   
1        103 MB  For ages 18 and up   
2      39.86 MB  For ages 12 and up   
3       4.59 MB  For ages 12 and up   
4     182.41 MB  For ages 12 and up   
...         ...                 ...   
3892   10.11 MB   For ages 3 and up   
3893    7.24 MB   For ages 3 and up   
3894   38.95 MB   For ages 3 and up   
3895   77.08 MB   For ages 7 and up   
3896   144.8 MB  For ages 12 and up   

                                              Languages  
0                                 English(UnitedStates)  
1                                 English(UnitedStates)  
2     English(UnitedStates)   English(UnitedKingdom)...  
3                                 English(UnitedStates)  
4     English(UnitedStates)   العربية(المملكةالعربية...  
...                                                 ...  
3892                     English(UnitedStates)   中文(中国)  
3893  English(UnitedStates)   English(UnitedKingdom)...  
3894  Deutsch(Deutschland)   English(UnitedStates)  ...  
3895  English(UnitedStates)   Deutsch(Deutschland)  ...  
3896  English(UnitedStates)   Deutsch(Deutschland)  ...  

[3897 rows x 9 columns]

In [3]:
data_df = data_df.dropna(subset=['Date of Release', 'Size', 'Languages'])
data_df


Name     Price  \
0                   WhatsApp Desktop      Free   
1                   Telegram Desktop      Free   
2     Amazon Prime Video for Windows      Free   
3                          Instagram      Free   
4                      Spotify Music      Free   
...                              ...       ...   
3892           Vegas Slots Machine *  ₹ 109.00   
3893              Crossword Puzzle +  ₹ 109.00   
3894                     Rescue Team  ₹ 219.00   
3895                  Doodle Kingdom   ₹ 29.00   
3896                    Doodle Devil   ₹ 29.00   

                                            Description  \
0     With WhatsApp on the desktop, you can seamless...   
1     Pure instant messaging — simple, fast, secure,...   
2     Watch movies and TV shows recommended for you,...   
3     Bringing you closer to the people and things y...   
4     Love music? Play your favorite songs and album...   
...                                                 ...   
3892  Windows version Vegas style slot machine casin...   
3893  Crossword Puzzle is a casual crossword and cro...   
3894  Mother Nature has done a number on an island p...   
3895  It's time to get MEDIEVAL!\r\n\r\nFrom the cre...   
3896  Great Halloween Sale! 50% off all in-app purch...   

                                   Publisher Date of Release       Category  \
0                              WhatsApp Inc.          1/2/17         Social   
1                     Telegram Messenger LLP          3/4/17         Social   
2     Amazon Development Centre (London) Ltd      24-02-2020  Entertainment   
3                                  Instagram      26-02-2016         Social   
4                                 Spotify AB      26-05-2017  Entertainment   
...                                      ...             ...            ...   
3892                               Cool Inc.      30-01-2018          Games   
3893                                App Best      30-01-2018          Games   
3894               Alawar Entertainment Inc.      29-05-2013          Games   
3895                             JoyBits Ltd      25-11-2013          Games   
3896                             JoyBits Ltd      24-09-2012          Games   

           Size          Age Rating  \
0     379.39 MB   For ages 3 and up   
1        103 MB  For ages 18 and up   
2      39.86 MB  For ages 12 and up   
3       4.59 MB  For ages 12 and up   
4     182.41 MB  For ages 12 and up   
...         ...                 ...   
3892   10.11 MB   For ages 3 and up   
3893    7.24 MB   For ages 3 and up   
3894   38.95 MB   For ages 3 and up   
3895   77.08 MB   For ages 7 and up   
3896   144.8 MB  For ages 12 and up   

                                              Languages  
0                                 English(UnitedStates)  
1                                 English(UnitedStates)  
2     English(UnitedStates)   English(UnitedKingdom)...  
3                                 English(UnitedStates)  
4     English(UnitedStates)   العربية(المملكةالعربية...  
...                                                 ...  
3892                     English(UnitedStates)   中文(中国)  
3893  English(UnitedStates)   English(UnitedKingdom)...  
3894  Deutsch(Deutschland)   English(UnitedStates)  ...  
3895  English(UnitedStates)   Deutsch(Deutschland)  ...  
3896  English(UnitedStates)   Deutsch(Deutschland)  ...  

[3535 rows x 9 columns]

### Text Cleaning

In [4]:
import re
import string
import nltk

In [5]:
def clean_text(text):
    text = text.lower()                                  # lower-case all characters
#     text =  re.sub(r'@\S+', '',text)                     # remove twitter handles
    text =  re.sub(r'http\S+', '',text)                  # remove urls
    text =  re.sub(r'pic.\S+', '',text) 
    text =  re.sub(r"[^a-zA-Z+']", ' ',text)             # only keeps characters
    text = re.sub(r'\s+[a-zA-Z]\s+', ' ', text+' ')      # keep words with length>1 only
    text = "".join([i for i in text if i not in string.punctuation])
    words = nltk.tokenize.word_tokenize(text)
    stopwords = nltk.corpus.stopwords.words('english')   # remove stopwords
    text = " ".join([i for i in words if i not in stopwords and len(i)>2])
    text= re.sub("\s[\s]+", " ",text).strip()            # remove repeated/leading/trailing spaces
    return text

In [6]:
data_df['cleaned_description'] = data_df.Description.apply(clean_text)
data_df.head()

/var/folders/8g/4y5p6hq92t37fhjb_m38wr9h0000gn/T/ipykernel_22019/4103907943.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df['cleaned_description'] = data_df.Description.apply(clean_text)


Name Price  \
0                WhatsApp Desktop  Free   
1                Telegram Desktop  Free   
2  Amazon Prime Video for Windows  Free   
3                       Instagram  Free   
4                   Spotify Music  Free   

                                         Description  \
0  With WhatsApp on the desktop, you can seamless...   
1  Pure instant messaging — simple, fast, secure,...   
2  Watch movies and TV shows recommended for you,...   
3  Bringing you closer to the people and things y...   
4  Love music? Play your favorite songs and album...   

                                Publisher Date of Release       Category  \
0                           WhatsApp Inc.          1/2/17         Social   
1                  Telegram Messenger LLP          3/4/17         Social   
2  Amazon Development Centre (London) Ltd      24-02-2020  Entertainment   
3                               Instagram      26-02-2016         Social   
4                              Spotify AB      26-05-2017  Entertainment   

        Size          Age Rating  \
0  379.39 MB   For ages 3 and up   
1     103 MB  For ages 18 and up   
2   39.86 MB  For ages 12 and up   
3    4.59 MB  For ages 12 and up   
4  182.41 MB  For ages 12 and up   

                                           Languages  \
0                              English(UnitedStates)   
1                              English(UnitedStates)   
2  English(UnitedStates)   English(UnitedKingdom)...   
3                              English(UnitedStates)   
4  English(UnitedStates)   العربية(المملكةالعربية...   

                                 cleaned_description  
0  whatsapp desktop seamlessly sync chats compute...  
1  pure instant messaging simple fast secure sync...  
2  watch movies shows recommended including amazo...  
3  bringing closer people things love instagram f...  
4  love music play favorite songs albums free win...

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

x_train, x_test, y_train, y_test = train_test_split(data_df['cleaned_description'], data_df['Age Rating'], test_size=0.2, random_state=42)

vectorizer = CountVectorizer()

x_train_cv = vectorizer.fit_transform(x_train)
x_test_cv = vectorizer.transform(x_test)


In [9]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

nb_classifier = MultinomialNB()

nb_classifier.fit(x_train_cv, y_train)

y_pred_cv = nb_classifier.predict(x_test_cv)

# Calculate performance metrics
accuracy = accuracy_score(y_test, y_pred_cv)
precision = precision_score(y_test, y_pred_cv, average='weighted')
recall = recall_score(y_test, y_pred_cv, average='weighted')
f1 = f1_score(y_test, y_pred_cv, average='weighted')

print("Overall Performance Metrics(Unigram):")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# Calculate performance metrics for each label
labels = ['Not Rated', 
          'For ages 18 and up', 
          'For ages 16 and up', 
          'For ages 7 and up', 
          'For ages 12 and up', 
          'For ages 3 and up']


classification_report_result_cv = classification_report(y_test, y_pred_cv, labels=labels)
print("\nPerformance Metrics for Each Label:")
print(classification_report_result_cv)

Overall Performance Metrics(Unigram):
Accuracy: 0.809052333804809
Precision: 0.8192001188861852
Recall: 0.809052333804809
F1 Score: 0.7969958767992029

Performance Metrics for Each Label:
                    precision    recall  f1-score   support

         Not Rated       0.00      0.00      0.00         4
For ages 18 and up       1.00      0.07      0.12        15
For ages 16 and up       0.25      0.21      0.23        14
 For ages 7 and up       0.34      0.72      0.46        43
For ages 12 and up       0.43      0.19      0.26        64
 For ages 3 and up       0.91      0.93      0.92       567

          accuracy                           0.81       707
         macro avg       0.49      0.35      0.33       707
      weighted avg       0.82      0.81      0.80       707



In [21]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Create SVM classifier
svm_classifier = SVC(kernel='linear')

# Fit the classifier on the training data
svm_classifier.fit(x_train_cv, y_train)

# Predict on the test data
y_pred_svm = svm_classifier.predict(x_test_cv)

# Calculate performance metrics
accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm, average='weighted')
recall_svm = recall_score(y_test, y_pred_svm, average='weighted')
f1_svm = f1_score(y_test, y_pred_svm, average='weighted')

print("Overall Performance Metrics (SVM):")
print("Accuracy:", accuracy_svm)
print("Precision:", precision_svm)
print("Recall:", recall_svm)
print("F1 Score:", f1_svm)

# Calculate performance metrics for each label
labels = ['Not Rated', 
          'For ages 18 and up', 
          'For ages 16 and up', 
          'For ages 7 and up', 
          'For ages 12 and up', 
          'For ages 3 and up']


# Calculate performance metrics for each label
classification_report_result_svm = classification_report(y_test, y_pred_svm, labels=labels)
print("\nPerformance Metrics for Each Label (SVM):")
print(classification_report_result_svm)


Overall Performance Metrics (SVM):
Accuracy: 0.8147100424328148
Precision: 0.8041090406333119
Recall: 0.8147100424328148
F1 Score: 0.8081340913010711

Performance Metrics for Each Label (SVM):
                    precision    recall  f1-score   support

         Not Rated       0.00      0.00      0.00         4
For ages 18 and up       0.56      0.33      0.42        15
For ages 16 and up       0.26      0.36      0.30        14
 For ages 7 and up       0.39      0.37      0.38        43
For ages 12 and up       0.42      0.34      0.38        64
 For ages 3 and up       0.90      0.93      0.92       567

          accuracy                           0.81       707
         macro avg       0.42      0.39      0.40       707
      weighted avg       0.80      0.81      0.81       707



### Error Analysis

In [11]:
###multinb
misclassified_examples_all = {}

# Initialize dictionary to store misclassified examples for each category
for label in labels:
    misclassified_examples_all[label] = []

# Iterate through test set predictions
for i in range(len(y_test)):
    # Check if the prediction doesn't match the ground truth label
    if y_pred_cv[i] != y_test.iloc[i]:
        # Store the misclassified example along with its predicted and actual labels
        misclassified_examples_all[y_test.iloc[i]].append((x_test.iloc[i], y_pred_cv[i], y_test.iloc[i]))

# Print misclassified examples for each category
for label in labels:
    print(f"Misclassified Examples in the '{label}' Age Rating:")
    for example in misclassified_examples_all[label][:3]:
        print("Description:", example[0])
        print("Predicted Label:", example[1])
        print("Actual Label:", example[2])
        print()


Misclassified Examples in the 'Not Rated' Age Rating:
Description: onenote digital notebook capturing organizing everything across devices jot ideas keep track classroom meeting notes clip web make list well draw sketch ideas type write draw write anywhere page unleash imagination use devices pen finger write draw multiple types pens highlighters take notes white background add grid ruled lines easier drawing writing capture anything quickly take note clicking note button action center supported pens send websites recipes documents onenote using share charm microsoft edge clipper office lens dozens apps services get organized search find anything notes including handwritten ink text quickly access recent notes complete visual previews page one click access lists check boxes made teamwork easily share notebooks notes colleagues family friends plan vacations share meeting minutes lecture notes people around edit notes together see changes real time always notes travel whether youre home 

In [12]:
import numpy as np

# Initialize confusion matrix array
num_classes = len(labels)
confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

# Map labels to indices
label_to_index = {label: index for index, label in enumerate(labels)}

# Iterate through predictions and labels to populate the confusion matrix
for pred, true_label in zip(y_pred_cv, y_test):
    pred_index = label_to_index[pred]
    true_index = label_to_index[true_label]
    confusion_matrix[true_index, pred_index] += 1

# Print the confusion matrix array
print("Confusion Matrix of Classification:")
print(confusion_matrix)


Confusion Matrix of Classification:
[[  0   0   0   0   0   4]
 [  0   1   3   4   3   4]
 [  0   0   3   9   1   1]
 [  0   0   2  31   2   8]
 [  0   0   2  18  12  32]
 [  1   0   2  29  10 525]]


In [13]:
label_to_index

{'Not Rated': 0,
 'For ages 18 and up': 1,
 'For ages 16 and up': 2,
 'For ages 7 and up': 3,
 'For ages 12 and up': 4,
 'For ages 3 and up': 5}

In [22]:
###svm
misclassified_examples_all = {}

# Initialize dictionary to store misclassified examples for each category
for label in labels:
    misclassified_examples_all[label] = []

# Iterate through test set predictions
for i in range(len(y_test)):
    # Check if the prediction doesn't match the ground truth label
    if y_pred_svm[i] != y_test.iloc[i]:
        # Store the misclassified example along with its predicted and actual labels
        misclassified_examples_all[y_test.iloc[i]].append((x_test.iloc[i], y_pred_svm[i], y_test.iloc[i]))

# Print misclassified examples for each category
for label in labels:
    print(f"Misclassified Examples in the '{label}' Age Rating:")
    for example in misclassified_examples_all[label][:3]:
        print("Description:", example[0])
        print("Predicted Label:", example[1])
        print("Actual Label:", example[2])
        print()


Misclassified Examples in the 'Not Rated' Age Rating:
Description: onenote digital notebook capturing organizing everything across devices jot ideas keep track classroom meeting notes clip web make list well draw sketch ideas type write draw write anywhere page unleash imagination use devices pen finger write draw multiple types pens highlighters take notes white background add grid ruled lines easier drawing writing capture anything quickly take note clicking note button action center supported pens send websites recipes documents onenote using share charm microsoft edge clipper office lens dozens apps services get organized search find anything notes including handwritten ink text quickly access recent notes complete visual previews page one click access lists check boxes made teamwork easily share notebooks notes colleagues family friends plan vacations share meeting minutes lecture notes people around edit notes together see changes real time always notes travel whether youre home 

In [23]:
import numpy as np

# Initialize confusion matrix array
num_classes = len(labels)
confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

# Map labels to indices
label_to_index = {label: index for index, label in enumerate(labels)}

# Iterate through predictions and labels to populate the confusion matrix
for pred, true_label in zip(y_pred_svm, y_test):
    pred_index = label_to_index[pred]
    true_index = label_to_index[true_label]
    confusion_matrix[true_index, pred_index] += 1

# Print the confusion matrix array
print("Confusion Matrix of SVM Classification:")
print(confusion_matrix)


Confusion Matrix of SVM Classification:
[[  0   0   0   0   0   4]
 [  0   5   2   0   1   7]
 [  0   1   5   4   2   2]
 [  0   0   5  16   4  18]
 [  0   2   4  11  22  25]
 [  2   1   3  10  23 528]]


In [ ]:
### Tuned
### GridSearch MultiNB

In [18]:
from sklearn.model_selection import GridSearchCV

# Define parameter grid for tuning
param_grid = {'alpha': [0.1, 0.5, 1.0, 2.0]}

# Instantiate GridSearchCV
grid_search = GridSearchCV(MultinomialNB(), param_grid, cv=5, scoring='f1')

# Fit the grid search to the data
grid_search.fit(x_train_cv, y_train)

# Print best parameters
print("Best Parameters:", grid_search.best_params_)

# Use the best estimator for prediction
best_nb_classifier = grid_search.best_estimator_
y_pred_cv_tuned = best_nb_classifier.predict(x_test_cv)

# Calculate performance metrics
accuracy_tuned = accuracy_score(y_test, y_pred_cv_tuned)
precision_tuned = precision_score(y_test, y_pred_cv_tuned, average='weighted')
recall_tuned = recall_score(y_test, y_pred_cv_tuned, average='weighted')
f1_tuned = f1_score(y_test, y_pred_cv_tuned, average='weighted')

print("\nOverall Performance Metrics (Tuned Multinomial NB):")
print("Accuracy:", accuracy_tuned)
print("Precision:", precision_tuned)
print("Recall:", recall_tuned)
print("F1 Score:", f1_tuned)

# Calculate performance metrics for each label
classification_report_result_cv_tuned = classification_report(y_test, y_pred_cv_tuned, labels=labels)
print("\nPerformance Metrics for Each Label (Tuned Multinomial NB):")
print(classification_report_result_cv_tuned)

Best Parameters: {'alpha': 0.1}

Overall Performance Metrics (Tuned Multinomial NB):
Accuracy: 0.8005657708628006
Precision: 0.8266737751667864
Recall: 0.8005657708628006
F1 Score: 0.8057079583269583

Performance Metrics for Each Label (Tuned Multinomial NB):
                    precision    recall  f1-score   support

         Not Rated       0.00      0.00      0.00         4
For ages 18 and up       0.62      0.33      0.43        15
For ages 16 and up       0.27      0.43      0.33        14
 For ages 7 and up       0.33      0.72      0.46        43
For ages 12 and up       0.46      0.28      0.35        64
 For ages 3 and up       0.93      0.89      0.91       567

          accuracy                           0.80       707
         macro avg       0.44      0.44      0.41       707
      weighted avg       0.83      0.80      0.81       707



/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 810, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 266, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line

In [19]:
import numpy as np

# Initialize confusion matrix array
num_classes = len(labels)
confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

# Map labels to indices
label_to_index = {label: index for index, label in enumerate(labels)}

# Iterate through predictions and labels to populate the confusion matrix
for pred, true_label in zip(y_pred_cv_tuned, y_test):
    pred_index = label_to_index[pred]
    true_index = label_to_index[true_label]
    confusion_matrix[true_index, pred_index] += 1

# Print the confusion matrix array
print("Confusion Matrix of Classification:")
print(confusion_matrix)


Confusion Matrix of Classification:
[[  0   0   0   0   0   4]
 [  0   5   2   4   1   3]
 [  0   1   6   7   0   0]
 [  0   0   2  31   2   8]
 [  0   2   6  15  18  23]
 [  1   0   6  36  18 506]]


In [20]:
label_to_index

{'Not Rated': 0,
 'For ages 18 and up': 1,
 'For ages 16 and up': 2,
 'For ages 7 and up': 3,
 'For ages 12 and up': 4,
 'For ages 3 and up': 5}

In [ ]:
### GridSearch SVM

In [24]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],  # Penalty parameter C of the error term
}

# Create SVM classifier
svm_classifier = SVC()

# Create GridSearchCV object
grid_search = GridSearchCV(svm_classifier, param_grid, cv=5, scoring='accuracy')

# Fit the GridSearchCV object to the training data
grid_search.fit(x_train_cv, y_train)

# Get the best parameters and best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print("Best Parameters:", best_params)
print("Best Score:", best_score)

# Predict on the test data using the best model
best_svm_classifier = grid_search.best_estimator_
y_pred_svm_grid = best_svm_classifier.predict(x_test_cv)

# Calculate performance metrics
accuracy_svm_grid = accuracy_score(y_test, y_pred_svm_grid)
precision_svm_grid = precision_score(y_test, y_pred_svm_grid, average='weighted')
recall_svm_grid = recall_score(y_test, y_pred_svm_grid, average='weighted')
f1_svm_grid = f1_score(y_test, y_pred_svm_grid, average='weighted')

print("Overall Performance Metrics (SVM with Grid Search):")
print("Accuracy:", accuracy_svm_grid)
print("Precision:", precision_svm_grid)
print("Recall:", recall_svm_grid)
print("F1 Score:", f1_svm_grid)

# Calculate performance metrics for each label
classification_report_result_svm_grid = classification_report(y_test, y_pred_svm_grid, labels=labels)
print("\nPerformance Metrics for Each Label (SVM with Grid Search):")
print(classification_report_result_svm_grid)


/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


Best Parameters: {'C': 10}
Best Score: 0.8359210732042903
Overall Performance Metrics (SVM with Grid Search):
Accuracy: 0.8415841584158416
Precision: 0.8131027388453131
Recall: 0.8415841584158416
F1 Score: 0.8154011745288301

Performance Metrics for Each Label (SVM with Grid Search):
                    precision    recall  f1-score   support

         Not Rated       0.00      0.00      0.00         4
For ages 18 and up       0.83      0.33      0.48        15
For ages 16 and up       0.45      0.36      0.40        14
 For ages 7 and up       0.40      0.33      0.36        43
For ages 12 and up       0.60      0.23      0.34        64
 For ages 3 and up       0.88      0.98      0.93       567

          accuracy                           0.84       707
         macro avg       0.53      0.37      0.42       707
      weighted avg       0.81      0.84      0.82       707



/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, 

In [25]:
import numpy as np

# Initialize confusion matrix array
num_classes = len(labels)
confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

# Map labels to indices
label_to_index = {label: index for index, label in enumerate(labels)}

# Iterate through predictions and labels to populate the confusion matrix
for pred, true_label in zip(y_pred_svm_grid, y_test):
    pred_index = label_to_index[pred]
    true_index = label_to_index[true_label]
    confusion_matrix[true_index, pred_index] += 1

# Print the confusion matrix array
print("Confusion Matrix of Classification:")
print(confusion_matrix)


Confusion Matrix of Classification:
[[  0   0   0   0   0   4]
 [  0   5   2   0   0   8]
 [  0   0   5   3   3   3]
 [  0   0   3  14   4  22]
 [  0   1   1  10  15  37]
 [  0   0   0   8   3 556]]
