In [1]:
import pandas as pd

In [2]:
data_file = "windows_store_top15_data.csv"

data_df = pd.read_csv(data_file)

data_df

Name     Price  \
0                   WhatsApp Desktop      Free   
1                   Telegram Desktop      Free   
2     Amazon Prime Video for Windows      Free   
3                          Instagram      Free   
4                      Spotify Music      Free   
...                              ...       ...   
3892           Vegas Slots Machine *  ₹ 109.00   
3893              Crossword Puzzle +  ₹ 109.00   
3894                     Rescue Team  ₹ 219.00   
3895                  Doodle Kingdom   ₹ 29.00   
3896                    Doodle Devil   ₹ 29.00   

                                            Description  \
0     With WhatsApp on the desktop, you can seamless...   
1     Pure instant messaging — simple, fast, secure,...   
2     Watch movies and TV shows recommended for you,...   
3     Bringing you closer to the people and things y...   
4     Love music? Play your favorite songs and album...   
...                                                 ...   
3892  Windows version Vegas style slot machine casin...   
3893  Crossword Puzzle is a casual crossword and cro...   
3894  Mother Nature has done a number on an island p...   
3895  It's time to get MEDIEVAL!\r\n\r\nFrom the cre...   
3896  Great Halloween Sale! 50% off all in-app purch...   

                                   Publisher Date of Release       Category  \
0                              WhatsApp Inc.          1/2/17         Social   
1                     Telegram Messenger LLP          3/4/17         Social   
2     Amazon Development Centre (London) Ltd      24-02-2020  Entertainment   
3                                  Instagram      26-02-2016         Social   
4                                 Spotify AB      26-05-2017  Entertainment   
...                                      ...             ...            ...   
3892                               Cool Inc.      30-01-2018          Games   
3893                                App Best      30-01-2018          Games   
3894               Alawar Entertainment Inc.      29-05-2013          Games   
3895                             JoyBits Ltd      25-11-2013          Games   
3896                             JoyBits Ltd      24-09-2012          Games   

           Size          Age Rating  \
0     379.39 MB   For ages 3 and up   
1        103 MB  For ages 18 and up   
2      39.86 MB  For ages 12 and up   
3       4.59 MB  For ages 12 and up   
4     182.41 MB  For ages 12 and up   
...         ...                 ...   
3892   10.11 MB   For ages 3 and up   
3893    7.24 MB   For ages 3 and up   
3894   38.95 MB   For ages 3 and up   
3895   77.08 MB   For ages 7 and up   
3896   144.8 MB  For ages 12 and up   

                                              Languages  
0                                 English(UnitedStates)  
1                                 English(UnitedStates)  
2     English(UnitedStates)   English(UnitedKingdom)...  
3                                 English(UnitedStates)  
4     English(UnitedStates)   العربية(المملكةالعربية...  
...                                                 ...  
3892                     English(UnitedStates)   中文(中国)  
3893  English(UnitedStates)   English(UnitedKingdom)...  
3894  Deutsch(Deutschland)   English(UnitedStates)  ...  
3895  English(UnitedStates)   Deutsch(Deutschland)  ...  
3896  English(UnitedStates)   Deutsch(Deutschland)  ...  

[3897 rows x 9 columns]

### Data Engineering

In [3]:
data_df.isna().sum()

Name                 0
Price                0
Description          0
Publisher            0
Date of Release      6
Category             0
Size               315
Age Rating           0
Languages           52
dtype: int64

In [4]:
data_df[data_df['Date of Release'].isna()]

Name  \
2940  Totally Accurate Battle Simulator   
3043            Grounded - Game Preview   
3067                          Craftopia   
3313  Second Extinction™ (Game Preview)   
3458      Black Skylands (Game Preview)   
3780          Starmancer (Game Preview)   

                                                  Price  \
2940  Included\r\n            \n\n\n+\n with  Game Pass   
3043     Included\r\n            \n\n\n with  Game Pass   
3067     Included\r\n            \n\n\n with  Game Pass   
3313     Included\r\n            \n\n\n with  Game Pass   
3458                                         ₹ 1,099.00   
3780     Included\r\n            \n\n\n with  Game Pass   

                                            Description           Publisher  \
2940  Be the leader of red and blue wobblers from an...            Landfall   
3043  This game is a work in progress. It may or may...   Xbox Game Studios   
3067  This game is still under development, and its ...   POCKET PAIR, Inc.   
3313  This game is a work in progress. It may or may...  Systemic Reaction™   
3458  This game is a work in progress. It may or may...           tinyBuild   
3780  This game is a work in progress. It may or may...         Chucklefish   

     Date of Release Category       Size          Age Rating  \
2940             NaN    Games        NaN   For ages 7 and up   
3043             NaN    Games        NaN  For ages 12 and up   
3067             NaN    Games        NaN  For ages 16 and up   
3313             NaN    Games        NaN  For ages 16 and up   
3458             NaN    Games        NaN  For ages 16 and up   
3780             NaN    Games  334.73 MB   For ages 7 and up   

                                              Languages  
2940  English(UnitedStates)   Español(España,Alfabet...  
3043  English(UnitedStates)   Deutsch(Deutschland)  ...  
3067                              English(UnitedStates)  
3313  English(UnitedStates)   Français(France)   Deu...  
3458                              English(UnitedStates)  
3780                              English(UnitedStates)

In [5]:
data_df[data_df['Size'].isna()]

Name  \
959          Asphalt 9: Legends   
981        Forza Horizon 4 Demo   
997             eFootball™ 2022   
1017   Hello Neighbor 2 Alpha 1   
1072                Hello Guest   
...                         ...   
3870                 Kathy Rain   
3876                Observation   
3878       Deliver Us The Moon.   
3880  Operencia: The Stolen Sun   
3890                  SkateBIRD   

                                               Price  \
959                                             Free   
981                                             Free   
997                                             Free   
1017                                            Free   
1072                                            Free   
...                                              ...   
3870                                        ₹ 824.00   
3876                                      ₹ 1,349.00   
3878                                      ₹ 1,349.00   
3880                                      ₹ 1,624.00   
3890  Included\r\n            \n\n\n with  Game Pass   

                                            Description  \
959   Take on the world’s most fearless drivers and ...   
981   Dynamic seasons change everything at the world...   
997   From "PES" to "eFootball™"\r\nGet ready to kic...   
1017  Hello Neighbor 2 is a Stealth Horror Game wher...   
1072  Welcome to Hello Guest, a stealth horror thril...   
...                                                 ...   
3870  Set in the 90's, Kathy Rain tells the story of...   
3876  Observation is a sci-fi thriller uncovering wh...   
3878  Deliver Us The Moon is a Sci-Fi thriller set i...   
3880  Zen Studios’ modern homage to classic first-pe...   
3890  Grind on bendy straws, kickflip over staplers,...   

                         Publisher Date of Release Category Size  \
959                    Gameloft SE      18-07-2018    Games  NaN   
981              Microsoft Studios         12/9/18    Games  NaN   
997   Konami Digital Entertainment      30-09-2021   Sports  NaN   
1017                     tinyBuild      23-07-2020    Games  NaN   
1072                     tinyBuild      13-06-2020    Games  NaN   
...                            ...             ...      ...  ...   
3870                      Raw Fury      24-09-2020    Games  NaN   
3876              Devolver Digital      25-06-2020    Games  NaN   
3878             Wired Productions      23-04-2020    Games  NaN   
3880                   Zen Studios      29-03-2019    Games  NaN   
3890            Glass Bottom Games      16-09-2021    Games  NaN   

              Age Rating                                          Languages  
959    For ages 7 and up  English(UnitedStates)   Deutsch(Deutschland)  ...  
981    For ages 3 and up  English(UnitedStates)   English(Australia)   E...  
997    For ages 3 and up  English(UnitedKingdom)   English(UnitedStates)...  
1017   For ages 7 and up                              English(UnitedStates)  
1072  For ages 12 and up                              English(UnitedStates)  
...                  ...                                                ...  
3870  For ages 16 and up  English(UnitedStates)   Deutsch(Deutschland)  ...  
3876  For ages 16 and up                              English(UnitedStates)  
3878  For ages 12 and up                              English(UnitedStates)  
3880  For ages 12 and up  English(UnitedStates)   Français(France)   Ita...  
3890  For ages 12 and up  English(UnitedStates)   Español(España,Alfabet...  

[315 rows x 9 columns]

In [6]:
data_df[data_df['Size'].isna()]['Category'].unique()

array(['Games', 'Sports'], dtype=object)

In [7]:
data_df[data_df['Languages'].isna()]

Name  \
2918        Minecraft for Windows 10 Starter Collection   
2921         Minecraft for Windows 10 Master Collection   
2928                        Age of Empires IV Pre-Order   
2946  Minecraft Dungeons Ultimate DLC Bundle - Windo...   
2947                   DOOM Eternal Deluxe Edition (PC)   
2956            Forza Horizon 4 Ultimate Add-Ons Bundle   
2962             Forza Horizon 5 Premium Add-Ons Bundle   
2966                    Just Cause 4 - Complete Edition   
2981                                    Imperator: Rome   
2989                              Maneater Apex Edition   
2990                          Metro Exodus Gold Edition   
2997    【Pre-Order】 eFootball™ 2022 Premium Player Pack   
3003              Age of Empires: Definitive Collection   
3016                                  Metro Saga Bundle   
3034                           Halo Infinite (Campaign)   
3039                                        Halo: Reach   
3041                      Halo Wars 2: Complete Edition   
3042  Skyrim Special Edition + Fallout 4 G.O.T.Y Bun...   
3060                                Ori: The Collection   
3074                  Forza Horizon 4 Expansions Bundle   
3096                   DOOM Eternal: Year One Pass (PC)   
3115           Five Nights at Freddy's: Original Series   
3119                   Hearts of Iron IV: Cadet Edition   
3124         Remnant: From the Ashes - Complete Edition   
3128           Fallout 4: Game of the Year Edition (PC)   
3135     DOOM Eternal: The Ancient Gods - Part One (PC)   
3154                 Outer Wilds: Archaeologist Edition   
3172                 DOOM Eternal Standard Edition (PC)   
3177          Kingdom Come: Deliverance - Royal Edition   
3180                                        Crackdown 3   
3181                       SCARLET NEXUS Deluxe Edition   
3189      Life is Strange: True Colors - Deluxe Upgrade   
3212     DOOM Eternal: The Ancient Gods - Part Two (PC)   
3219                              Train Sim World® 2020   
3246                                Gears Triple Bundle   
3251       Yakuza: Like a Dragon Legendary Hero Edition   
3282         Fallout 76: Steel Dawn Deluxe Edition (PC)   
3305                         Stellaris - Galaxy Edition   
3344                   Wolfenstein II: Standard Edition   
3354                    Phoenix Point: Year One Edition   
3363            Pillars of Eternity: Definitive Edition   
3451                                       Conan Exiles   
3508                 Yakuza: Like a Dragon Hero Edition   
3509                          Tell Me Why: Chapters 1-3   
3532              GreedFall - Gold Edition (Windows 10)   
3586                Children of Morta: Complete Edition   
3599                    SCARLET NEXUS Brain Punk Bundle   
3639       Pinball FX3 - Marvel Pinball: Cinematic Pack   
3698        Pinball FX3 - Zen Originals Season 1 Bundle   
3733        Metro Exodus - Sam's Story Enhanced Edition   
3741                          Pinball FX3 - Sci-Fi Pack   
3866                           CODE VEIN Deluxe Edition   

                                                  Price  \
2918                                         ₹ 1,674.00   
2921                                         ₹ 2,724.00   
2928                                         ₹ 3,999.00   
2946  Full price was ₹ 1,099.00\n₹ 1,099.00\n \nNow ...   
2947  Full price was ₹ 4,999.00\n₹ 4,999.00\n \nNow ...   
2956  Full price was ₹ 3,399.00\n₹ 3,399.00\n \nNow ...   
2962  Full price was ₹ 3,399.00\n₹ 3,399.00\n \nNow ...   
2966  Full price was ₹ 3,999.00\n₹ 3,999.00\n \nNow ...   
2981                                         ₹ 2,174.00   
2989  Full price was ₹ 2,724.00\n₹ 2,724.00\n \nNow ...   
2990                                           ₹ 824.00   
2997                                         ₹ 3,329.99   
3003  Included\r\n            \n\n\n+\n with  Game Pass   
3016                                         ₹ 3,249.00   
3034  Included\r\n            \n\n\n+\

In [8]:
data_df = data_df.dropna(subset=['Date of Release', 'Size', 'Languages'])
data_df


Name     Price  \
0                   WhatsApp Desktop      Free   
1                   Telegram Desktop      Free   
2     Amazon Prime Video for Windows      Free   
3                          Instagram      Free   
4                      Spotify Music      Free   
...                              ...       ...   
3892           Vegas Slots Machine *  ₹ 109.00   
3893              Crossword Puzzle +  ₹ 109.00   
3894                     Rescue Team  ₹ 219.00   
3895                  Doodle Kingdom   ₹ 29.00   
3896                    Doodle Devil   ₹ 29.00   

                                            Description  \
0     With WhatsApp on the desktop, you can seamless...   
1     Pure instant messaging — simple, fast, secure,...   
2     Watch movies and TV shows recommended for you,...   
3     Bringing you closer to the people and things y...   
4     Love music? Play your favorite songs and album...   
...                                                 ...   
3892  Windows version Vegas style slot machine casin...   
3893  Crossword Puzzle is a casual crossword and cro...   
3894  Mother Nature has done a number on an island p...   
3895  It's time to get MEDIEVAL!\r\n\r\nFrom the cre...   
3896  Great Halloween Sale! 50% off all in-app purch...   

                                   Publisher Date of Release       Category  \
0                              WhatsApp Inc.          1/2/17         Social   
1                     Telegram Messenger LLP          3/4/17         Social   
2     Amazon Development Centre (London) Ltd      24-02-2020  Entertainment   
3                                  Instagram      26-02-2016         Social   
4                                 Spotify AB      26-05-2017  Entertainment   
...                                      ...             ...            ...   
3892                               Cool Inc.      30-01-2018          Games   
3893                                App Best      30-01-2018          Games   
3894               Alawar Entertainment Inc.      29-05-2013          Games   
3895                             JoyBits Ltd      25-11-2013          Games   
3896                             JoyBits Ltd      24-09-2012          Games   

           Size          Age Rating  \
0     379.39 MB   For ages 3 and up   
1        103 MB  For ages 18 and up   
2      39.86 MB  For ages 12 and up   
3       4.59 MB  For ages 12 and up   
4     182.41 MB  For ages 12 and up   
...         ...                 ...   
3892   10.11 MB   For ages 3 and up   
3893    7.24 MB   For ages 3 and up   
3894   38.95 MB   For ages 3 and up   
3895   77.08 MB   For ages 7 and up   
3896   144.8 MB  For ages 12 and up   

                                              Languages  
0                                 English(UnitedStates)  
1                                 English(UnitedStates)  
2     English(UnitedStates)   English(UnitedKingdom)...  
3                                 English(UnitedStates)  
4     English(UnitedStates)   العربية(المملكةالعربية...  
...                                                 ...  
3892                     English(UnitedStates)   中文(中国)  
3893  English(UnitedStates)   English(UnitedKingdom)...  
3894  Deutsch(Deutschland)   English(UnitedStates)  ...  
3895  English(UnitedStates)   Deutsch(Deutschland)  ...  
3896  English(UnitedStates)   Deutsch(Deutschland)  ...  

[3535 rows x 9 columns]

In [9]:
data_df['Category'].unique()

array(['Social', 'Entertainment', 'Productivity', 'Developer Tools',
       'Personalization', 'Utilities & Tools', 'Multimedia Design',
       'Business', 'Education', 'Security', 'Books & Reference',
       'Lifestyle', 'Sports', 'Games', 'Educational'], dtype=object)

In [10]:
import numpy as np

In [11]:
un, count = np.unique(data_df.Category.values, return_counts=True)
count, un = zip(*sorted(zip(count, un)))
count = list(count)
un = list(un)
count.reverse()
un.reverse()
trending_categories = list(zip(un[:21], count[:21]))
print("Trending Categories:")
print(trending_categories)


Trending Categories:
[('Games', 1520), ('Entertainment', 447), ('Utilities & Tools', 413), ('Productivity', 287), ('Personalization', 259), ('Education', 143), ('Business', 130), ('Books & Reference', 75), ('Multimedia Design', 54), ('Sports', 46), ('Developer Tools', 44), ('Educational', 41), ('Social', 26), ('Lifestyle', 26), ('Security', 24)]


In [12]:
un, count = np.unique(data_df["Age Rating"], return_counts=True)
count = list(count)
un = list(un)
count, un = zip(*sorted(zip(count, un)))
age_rating_counts = list(zip(un, count))
print("Age Rating Counts:")
print(age_rating_counts)


Age Rating Counts:
[('Not Rated', 8), ('For ages 18 and up', 67), ('For ages 16 and up', 128), ('For ages 7 and up', 243), ('For ages 12 and up', 284), ('For ages 3 and up', 2805)]


In [13]:
import itertools

un, count = np.unique(list(itertools.chain.from_iterable([i.split() for i in data_df.Languages.values])), return_counts=True)
count, un = zip(*sorted(zip(count, un)))
count = list(count)
un = list(un)
count.reverse()
un.reverse()
top_languages = list(zip(un[:21], count[:21]))
print("Top 20 Supported Languages:")
print(top_languages)


Top 20 Supported Languages:
[('English(UnitedStates)', 3481), ('Deutsch(Deutschland)', 875), ('Français(France)', 847), ('Español(España,AlfabetizaciónInternacional)', 806), ('Italiano(Italia)', 791), ('中文(中国)', 761), ('Русский(Россия)', 750), ('日本語(日本)', 702), ('Português(Brasil)', 632), ('한국어(대한민국)', 548), ('Polski(Polska)', 408), ('Nederlands(Nederland)', 325), ('中文(香港特別行政區)', 319), ('Türkçe(Türkiye)', 309), ('Português(Portugal)', 255), ('Svenska(Sverige)', 232), ('中文(台灣)', 226), ('العربية(المملكةالعربيةالسعودية)', 208), ('Čeština(ČeskáRepublika)', 208), ('Українська(Україна)', 197), ('Suomi(Suomi)', 195)]


In [14]:
data_df

Name     Price  \
0                   WhatsApp Desktop      Free   
1                   Telegram Desktop      Free   
2     Amazon Prime Video for Windows      Free   
3                          Instagram      Free   
4                      Spotify Music      Free   
...                              ...       ...   
3892           Vegas Slots Machine *  ₹ 109.00   
3893              Crossword Puzzle +  ₹ 109.00   
3894                     Rescue Team  ₹ 219.00   
3895                  Doodle Kingdom   ₹ 29.00   
3896                    Doodle Devil   ₹ 29.00   

                                            Description  \
0     With WhatsApp on the desktop, you can seamless...   
1     Pure instant messaging — simple, fast, secure,...   
2     Watch movies and TV shows recommended for you,...   
3     Bringing you closer to the people and things y...   
4     Love music? Play your favorite songs and album...   
...                                                 ...   
3892  Windows version Vegas style slot machine casin...   
3893  Crossword Puzzle is a casual crossword and cro...   
3894  Mother Nature has done a number on an island p...   
3895  It's time to get MEDIEVAL!\r\n\r\nFrom the cre...   
3896  Great Halloween Sale! 50% off all in-app purch...   

                                   Publisher Date of Release       Category  \
0                              WhatsApp Inc.          1/2/17         Social   
1                     Telegram Messenger LLP          3/4/17         Social   
2     Amazon Development Centre (London) Ltd      24-02-2020  Entertainment   
3                                  Instagram      26-02-2016         Social   
4                                 Spotify AB      26-05-2017  Entertainment   
...                                      ...             ...            ...   
3892                               Cool Inc.      30-01-2018          Games   
3893                                App Best      30-01-2018          Games   
3894               Alawar Entertainment Inc.      29-05-2013          Games   
3895                             JoyBits Ltd      25-11-2013          Games   
3896                             JoyBits Ltd      24-09-2012          Games   

           Size          Age Rating  \
0     379.39 MB   For ages 3 and up   
1        103 MB  For ages 18 and up   
2      39.86 MB  For ages 12 and up   
3       4.59 MB  For ages 12 and up   
4     182.41 MB  For ages 12 and up   
...         ...                 ...   
3892   10.11 MB   For ages 3 and up   
3893    7.24 MB   For ages 3 and up   
3894   38.95 MB   For ages 3 and up   
3895   77.08 MB   For ages 7 and up   
3896   144.8 MB  For ages 12 and up   

                                              Languages  
0                                 English(UnitedStates)  
1                                 English(UnitedStates)  
2     English(UnitedStates)   English(UnitedKingdom)...  
3                                 English(UnitedStates)  
4     English(UnitedStates)   العربية(المملكةالعربية...  
...                                                 ...  
3892                     English(UnitedStates)   中文(中国)  
3893  English(UnitedStates)   English(UnitedKingdom)...  
3894  Deutsch(Deutschland)   English(UnitedStates)  ...  
3895  English(UnitedStates)   Deutsch(Deutschland)  ...  
3896  English(UnitedStates)   Deutsch(Deutschland)  ...  

[3535 rows x 9 columns]

### Text Cleaning

In [15]:
import re
import string
import nltk

In [16]:
def clean_text(text):
    text = text.lower()                                  # lower-case all characters
#     text =  re.sub(r'@\S+', '',text)                     # remove twitter handles
    text =  re.sub(r'http\S+', '',text)                  # remove urls
    text =  re.sub(r'pic.\S+', '',text) 
    text =  re.sub(r"[^a-zA-Z+']", ' ',text)             # only keeps characters
    text = re.sub(r'\s+[a-zA-Z]\s+', ' ', text+' ')      # keep words with length>1 only
    text = "".join([i for i in text if i not in string.punctuation])
    words = nltk.tokenize.word_tokenize(text)
    stopwords = nltk.corpus.stopwords.words('english')   # remove stopwords
    text = " ".join([i for i in words if i not in stopwords and len(i)>2])
    text= re.sub("\s[\s]+", " ",text).strip()            # remove repeated/leading/trailing spaces
    return text

In [17]:
data_df['cleaned_description'] = data_df.Description.apply(clean_text)
data_df.head()

/var/folders/8g/4y5p6hq92t37fhjb_m38wr9h0000gn/T/ipykernel_93994/4103907943.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df['cleaned_description'] = data_df.Description.apply(clean_text)


Name Price  \
0                WhatsApp Desktop  Free   
1                Telegram Desktop  Free   
2  Amazon Prime Video for Windows  Free   
3                       Instagram  Free   
4                   Spotify Music  Free   

                                         Description  \
0  With WhatsApp on the desktop, you can seamless...   
1  Pure instant messaging — simple, fast, secure,...   
2  Watch movies and TV shows recommended for you,...   
3  Bringing you closer to the people and things y...   
4  Love music? Play your favorite songs and album...   

                                Publisher Date of Release       Category  \
0                           WhatsApp Inc.          1/2/17         Social   
1                  Telegram Messenger LLP          3/4/17         Social   
2  Amazon Development Centre (London) Ltd      24-02-2020  Entertainment   
3                               Instagram      26-02-2016         Social   
4                              Spotify AB      26-05-2017  Entertainment   

        Size          Age Rating  \
0  379.39 MB   For ages 3 and up   
1     103 MB  For ages 18 and up   
2   39.86 MB  For ages 12 and up   
3    4.59 MB  For ages 12 and up   
4  182.41 MB  For ages 12 and up   

                                           Languages  \
0                              English(UnitedStates)   
1                              English(UnitedStates)   
2  English(UnitedStates)   English(UnitedKingdom)...   
3                              English(UnitedStates)   
4  English(UnitedStates)   العربية(المملكةالعربية...   

                                 cleaned_description  
0  whatsapp desktop seamlessly sync chats compute...  
1  pure instant messaging simple fast secure sync...  
2  watch movies shows recommended including amazo...  
3  bringing closer people things love instagram f...  
4  love music play favorite songs albums free win...

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

x_train, x_test, y_train, y_test = train_test_split(data_df['cleaned_description'], data_df['Category'], test_size=0.2, random_state=42)

vectorizer = CountVectorizer()

x_train_cv = vectorizer.fit_transform(x_train)
x_test_cv = vectorizer.transform(x_test)


In [19]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

nb_classifier = MultinomialNB()

nb_classifier.fit(x_train_cv, y_train)

y_pred_cv = nb_classifier.predict(x_test_cv)

# Calculate performance metrics
accuracy = accuracy_score(y_test, y_pred_cv)
precision = precision_score(y_test, y_pred_cv, average='weighted')
recall = recall_score(y_test, y_pred_cv, average='weighted')
f1 = f1_score(y_test, y_pred_cv, average='weighted')

print("Overall Performance Metrics(Unigram):")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# Calculate performance metrics for each label
labels = ['Social', 'Entertainment', 'Productivity', 'Developer Tools',
       'Personalization', 'Utilities & Tools', 'Multimedia Design',
       'Business', 'Education', 'Security', 'Books & Reference',
       'Lifestyle', 'Sports', 'Games', 'Educational']

classification_report_result_cv = classification_report(y_test, y_pred_cv, labels=labels)
print("\nPerformance Metrics for Each Label:")
print(classification_report_result_cv)

Overall Performance Metrics(Unigram):
Accuracy: 0.727015558698727
Precision: 0.6880919402297345
Recall: 0.727015558698727
F1 Score: 0.688676466835765

Performance Metrics for Each Label:
                   precision    recall  f1-score   support

           Social       0.00      0.00      0.00         5
    Entertainment       0.60      0.83      0.70       100
     Productivity       0.47      0.65      0.55        60
  Developer Tools       1.00      0.33      0.50         9
  Personalization       1.00      0.86      0.93        51
Utilities & Tools       0.50      0.49      0.49        78
Multimedia Design       0.00      0.00      0.00        13
         Business       0.00      0.00      0.00        27
        Education       0.65      0.38      0.48        34
         Security       1.00      0.25      0.40         4
Books & Reference       0.50      0.06      0.11        16
        Lifestyle       1.00      0.20      0.33         5
           Sports       0.67      0.18      0

/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, 

In [25]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Create SVM classifier
svm_classifier = SVC(kernel='linear')

# Fit the classifier on the training data
svm_classifier.fit(x_train_cv, y_train)

# Predict on the test data
y_pred_svm = svm_classifier.predict(x_test_cv)

# Calculate performance metrics
accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm, average='weighted')
recall_svm = recall_score(y_test, y_pred_svm, average='weighted')
f1_svm = f1_score(y_test, y_pred_svm, average='weighted')

print("Overall Performance Metrics (SVM):")
print("Accuracy:", accuracy_svm)
print("Precision:", precision_svm)
print("Recall:", recall_svm)
print("F1 Score:", f1_svm)

# Calculate performance metrics for each label
labels = ['Social', 'Entertainment', 'Productivity', 'Developer Tools',
       'Personalization', 'Utilities & Tools', 'Multimedia Design',
       'Business', 'Education', 'Security', 'Books & Reference',
       'Lifestyle', 'Sports', 'Games', 'Educational']


# Calculate performance metrics for each label
classification_report_result_svm = classification_report(y_test, y_pred_svm, labels=labels)
print("\nPerformance Metrics for Each Label (SVM):")
print(classification_report_result_svm)


Overall Performance Metrics (SVM):
Accuracy: 0.7171145685997171
Precision: 0.7301050299624052
Recall: 0.7171145685997171
F1 Score: 0.7208090727511048

Performance Metrics for Each Label (SVM):
                   precision    recall  f1-score   support

           Social       0.67      0.40      0.50         5
    Entertainment       0.72      0.58      0.64       100
     Productivity       0.47      0.45      0.46        60
  Developer Tools       0.57      0.44      0.50         9
  Personalization       0.98      0.90      0.94        51
Utilities & Tools       0.46      0.50      0.48        78
Multimedia Design       0.29      0.31      0.30        13
         Business       0.44      0.67      0.53        27
        Education       0.51      0.53      0.52        34
         Security       0.40      0.50      0.44         4
Books & Reference       0.38      0.38      0.38        16
        Lifestyle       0.33      0.40      0.36         5
           Sports       0.60      0.55 

In [ ]:
data_df['Category'].unique()

### Error Analysis

In [ ]:
# # Initialize an empty dictionary to store misclassified examples for each label
# misclassified_examples = {label: [] for label in labels}

# # Iterate through each test instance and check if it was misclassified
# for i in range(len(y_test)):
#     true_label = y_test.iloc[i]
#     predicted_label = y_pred_cv[i]
#     if true_label != predicted_label:
#         misclassified_examples[true_label].append((x_test.iloc[i], predicted_label))

# # Print misclassified examples for each label
# for label, examples in misclassified_examples.items():
#     print(f"Misclassified examples for label '{label}':")
#     for i, (example_text, predicted_label) in enumerate(examples[:3], 1):
#         original_label = y_test.iloc[i]
#         print(f"Example {i}:")
#         print(f"Original Label: {original_label}")
#         print(f"Text: {example_text}")
#         print(f"Predicted Label: {predicted_label}\n")


In [20]:
###multinb
misclassified_examples_all = {}

# Initialize dictionary to store misclassified examples for each category
for label in labels:
    misclassified_examples_all[label] = []

# Iterate through test set predictions
for i in range(len(y_test)):
    # Check if the prediction doesn't match the ground truth label
    if y_pred_cv[i] != y_test.iloc[i]:
        # Store the misclassified example along with its predicted and actual labels
        misclassified_examples_all[y_test.iloc[i]].append((x_test.iloc[i], y_pred_cv[i], y_test.iloc[i]))

# Print misclassified examples for each category
for label in labels:
    print(f"Misclassified Examples in the '{label}' Category:")
    for example in misclassified_examples_all[label][:3]:
        print("Description:", example[0])
        print("Predicted Label:", example[1])
        print("Actual Label:", example[2])
        print()


Misclassified Examples in the 'Social' Category:
Description: saver instagram pro lets download content click log account download photos videos stories followers following please note need instagram account use app account yet please create enjoy best performance saver instagram pro quick find easy save get original saver instagram pro saver instagram pro tested softpedia team granted clean software award using app youll forget strange unsafe web based downloaders instagram registered trademark rights belong instagram llc
Predicted Label: Entertainment
Actual Label: Social

Description: app instagram helps upload photos instagram conveniently view feeds likes free also upload images instagram one time payment app instagram third party app affiliated facebook inc instagram logo trademarks facebook inc
Predicted Label: Entertainment
Actual Label: Social

Description: line reshapes communication around globe letting enjoy messaging also free voice video calls wherever find download line 

In [21]:
import numpy as np

# Initialize confusion matrix array
num_classes = len(labels)
confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

# Map labels to indices
label_to_index = {label: index for index, label in enumerate(labels)}

# Iterate through predictions and labels to populate the confusion matrix
for pred, true_label in zip(y_pred_cv, y_test):
    pred_index = label_to_index[pred]
    true_index = label_to_index[true_label]
    confusion_matrix[true_index, pred_index] += 1

# Print the confusion matrix array
print("Confusion Matrix of Classification:")
print(confusion_matrix)


Confusion Matrix of Classification:
[[  0   3   1   0   0   1   0   0   0   0   0   0   0   0   0]
 [  0  83   2   0   0   1   0   0   2   0   0   0   0  12   0]
 [  0  10  39   0   0   8   0   0   0   0   0   0   0   3   0]
 [  0   1   1   3   0   4   0   0   0   0   0   0   0   0   0]
 [  0   4   2   0  44   0   0   0   0   0   0   0   0   1   0]
 [  0  15  15   0   0  38   0   0   3   0   0   0   0   7   0]
 [  0   8   5   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   7  10   0   0   9   0   0   0   0   0   0   0   1   0]
 [  0   1   5   0   0   4   0   0  13   0   1   0   0   9   1]
 [  0   0   1   0   0   2   0   0   0   1   0   0   0   0   0]
 [  0   4   1   0   0   7   0   0   2   0   1   0   0   1   0]
 [  0   1   1   0   0   1   0   0   0   0   0   1   0   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   2   9   0]
 [  0   0   0   0   0   1   0   0   0   0   0   0   1 286   1]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   1   3]]


In [22]:
label_to_index

{'Social': 0,
 'Entertainment': 1,
 'Productivity': 2,
 'Developer Tools': 3,
 'Personalization': 4,
 'Utilities & Tools': 5,
 'Multimedia Design': 6,
 'Business': 7,
 'Education': 8,
 'Security': 9,
 'Books & Reference': 10,
 'Lifestyle': 11,
 'Sports': 12,
 'Games': 13,
 'Educational': 14}

In [26]:
###svm
misclassified_examples_all = {}

# Initialize dictionary to store misclassified examples for each category
for label in labels:
    misclassified_examples_all[label] = []

# Iterate through test set predictions
for i in range(len(y_test)):
    # Check if the prediction doesn't match the ground truth label
    if y_pred_svm[i] != y_test.iloc[i]:
        # Store the misclassified example along with its predicted and actual labels
        misclassified_examples_all[y_test.iloc[i]].append((x_test.iloc[i], y_pred_svm[i], y_test.iloc[i]))

# Print misclassified examples for each category
for label in labels:
    print(f"Misclassified Examples in the '{label}' Category:")
    for example in misclassified_examples_all[label][:3]:
        print("Description:", example[0])
        print("Predicted Label:", example[1])
        print("Actual Label:", example[2])
        print()


Misclassified Examples in the 'Social' Category:
Description: saver instagram pro lets download content click log account download photos videos stories followers following please note need instagram account use app account yet please create enjoy best performance saver instagram pro quick find easy save get original saver instagram pro saver instagram pro tested softpedia team granted clean software award using app youll forget strange unsafe web based downloaders instagram registered trademark rights belong instagram llc
Predicted Label: Productivity
Actual Label: Social

Description: app instagram helps upload photos instagram conveniently view feeds likes free also upload images instagram one time payment app instagram third party app affiliated facebook inc instagram logo trademarks facebook inc
Predicted Label: Entertainment
Actual Label: Social

Description: whatsapp desktop seamlessly sync chats computer chat whatever device convenient
Predicted Label: Utilities & Tools
Actual 

In [27]:
import numpy as np

# Initialize confusion matrix array
num_classes = len(labels)
confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

# Map labels to indices
label_to_index = {label: index for index, label in enumerate(labels)}

# Iterate through predictions and labels to populate the confusion matrix
for pred, true_label in zip(y_pred_svm, y_test):
    pred_index = label_to_index[pred]
    true_index = label_to_index[true_label]
    confusion_matrix[true_index, pred_index] += 1

# Print the confusion matrix array
print("Confusion Matrix of SVM Classification:")
print(confusion_matrix)


Confusion Matrix of SVM Classification:
[[  2   1   1   0   0   1   0   0   0   0   0   0   0   0   0]
 [  0  58   8   0   0   7   8   6   7   0   1   2   0   3   0]
 [  0   3  27   0   0  16   2   5   0   1   3   2   0   1   0]
 [  0   1   1   4   0   2   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0  46   2   0   1   1   0   0   0   0   1   0]
 [  0  10  14   1   1  39   0   7   2   1   3   0   0   0   0]
 [  0   5   1   1   0   1   4   0   0   0   0   0   0   1   0]
 [  0   1   3   0   0   5   0  18   0   0   0   0   0   0   0]
 [  0   0   0   0   0   8   0   0  18   1   1   0   0   3   3]
 [  0   1   0   0   0   0   0   1   0   2   0   0   0   0   0]
 [  0   0   1   1   0   4   0   1   3   0   6   0   0   0   0]
 [  0   0   0   0   0   0   0   0   1   0   2   2   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   5   0]
 [  1   1   1   0   0   0   0   1   3   0   0   0   4 273   5]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   3   2]]


In [28]:
label_to_index

{'Social': 0,
 'Entertainment': 1,
 'Productivity': 2,
 'Developer Tools': 3,
 'Personalization': 4,
 'Utilities & Tools': 5,
 'Multimedia Design': 6,
 'Business': 7,
 'Education': 8,
 'Security': 9,
 'Books & Reference': 10,
 'Lifestyle': 11,
 'Sports': 12,
 'Games': 13,
 'Educational': 14}

In [ ]:
### GridSearch MultiNB

In [23]:
from sklearn.model_selection import GridSearchCV

# Define parameter grid for tuning
param_grid = {'alpha': [0.1, 0.5, 1.0, 2.0]}

# Instantiate GridSearchCV
grid_search = GridSearchCV(MultinomialNB(), param_grid, cv=5, scoring='f1')

# Fit the grid search to the data
grid_search.fit(x_train_cv, y_train)

# Print best parameters
print("Best Parameters:", grid_search.best_params_)

# Use the best estimator for prediction
best_nb_classifier = grid_search.best_estimator_
y_pred_cv_tuned = best_nb_classifier.predict(x_test_cv)

# Calculate performance metrics
accuracy_tuned = accuracy_score(y_test, y_pred_cv_tuned)
precision_tuned = precision_score(y_test, y_pred_cv_tuned, average='weighted')
recall_tuned = recall_score(y_test, y_pred_cv_tuned, average='weighted')
f1_tuned = f1_score(y_test, y_pred_cv_tuned, average='weighted')

print("\nOverall Performance Metrics (Tuned Multinomial NB):")
print("Accuracy:", accuracy_tuned)
print("Precision:", precision_tuned)
print("Recall:", recall_tuned)
print("F1 Score:", f1_tuned)

# Calculate performance metrics for each label
classification_report_result_cv_tuned = classification_report(y_test, y_pred_cv_tuned, labels=labels)
print("\nPerformance Metrics for Each Label (Tuned Multinomial NB):")
print(classification_report_result_cv_tuned)

Best Parameters: {'alpha': 0.1}

Overall Performance Metrics (Tuned Multinomial NB):
Accuracy: 0.7496463932107497
Precision: 0.7429344370267104
Recall: 0.7496463932107497
F1 Score: 0.7432339287554219

Performance Metrics for Each Label (Tuned Multinomial NB):
                   precision    recall  f1-score   support

           Social       0.75      0.60      0.67         5
    Entertainment       0.69      0.72      0.71       100
     Productivity       0.51      0.62      0.56        60
  Developer Tools       0.71      0.56      0.63         9
  Personalization       1.00      0.94      0.97        51
Utilities & Tools       0.51      0.49      0.50        78
Multimedia Design       0.40      0.31      0.35        13
         Business       0.53      0.33      0.41        27
        Education       0.58      0.53      0.55        34
         Security       0.33      0.25      0.29         4
Books & Reference       0.44      0.25      0.32        16
        Lifestyle       0.50   

/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 810, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 266, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 355, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/Users/meganhsu/anaconda3/envs/textmining/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wr

In [24]:
import numpy as np

# Initialize confusion matrix array
num_classes = len(labels)
confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

# Map labels to indices
label_to_index = {label: index for index, label in enumerate(labels)}

# Iterate through predictions and labels to populate the confusion matrix
for pred, true_label in zip(y_pred_cv_tuned, y_test):
    pred_index = label_to_index[pred]
    true_index = label_to_index[true_label]
    confusion_matrix[true_index, pred_index] += 1

# Print the confusion matrix array
print("Confusion Matrix of Classification:")
print(confusion_matrix)


Confusion Matrix of Classification:
[[  3   0   0   0   0   2   0   0   0   0   0   0   0   0   0]
 [  0  72   2   0   0   5   4   2   5   0   0   2   0   8   0]
 [  1   6  37   1   0  11   1   1   0   1   0   0   0   1   0]
 [  0   1   1   5   0   2   0   0   0   0   0   0   0   0   0]
 [  0   1   1   0  48   1   0   0   0   0   0   0   0   0   0]
 [  0  10  15   0   0  38   1   2   5   0   2   0   0   5   0]
 [  0   7   2   0   0   0   4   0   0   0   0   0   0   0   0]
 [  0   4  10   0   0   4   0   9   0   0   0   0   0   0   0]
 [  0   0   3   1   0   2   0   1  18   1   2   0   0   5   1]
 [  0   0   0   0   0   2   0   1   0   1   0   0   0   0   0]
 [  0   2   1   0   0   6   0   0   3   0   4   0   0   0   0]
 [  0   0   0   0   0   2   0   1   0   0   0   2   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   5   0]
 [  0   0   0   0   0   0   0   0   0   0   1   0   3 280   5]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   1   3]]


In [ ]:
label_to_index

### GridSearch SVM

In [29]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],  # Penalty parameter C of the error term
}

# Create SVM classifier
svm_classifier = SVC()

# Create GridSearchCV object
grid_search = GridSearchCV(svm_classifier, param_grid, cv=5, scoring='accuracy')

# Fit the GridSearchCV object to the training data
grid_search.fit(x_train_cv, y_train)

# Get the best parameters and best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print("Best Parameters:", best_params)
print("Best Score:", best_score)

# Predict on the test data using the best model
best_svm_classifier = grid_search.best_estimator_
y_pred_svm_grid = best_svm_classifier.predict(x_test_cv)

# Calculate performance metrics
accuracy_svm_grid = accuracy_score(y_test, y_pred_svm_grid)
precision_svm_grid = precision_score(y_test, y_pred_svm_grid, average='weighted')
recall_svm_grid = recall_score(y_test, y_pred_svm_grid, average='weighted')
f1_svm_grid = f1_score(y_test, y_pred_svm_grid, average='weighted')

print("Overall Performance Metrics (SVM with Grid Search):")
print("Accuracy:", accuracy_svm_grid)
print("Precision:", precision_svm_grid)
print("Recall:", recall_svm_grid)
print("F1 Score:", f1_svm_grid)

# Calculate performance metrics for each label
classification_report_result_svm_grid = classification_report(y_test, y_pred_svm_grid, labels=labels)
print("\nPerformance Metrics for Each Label (SVM with Grid Search):")
print(classification_report_result_svm_grid)


Best Parameters: {'C': 10}
Best Score: 0.7245354764063917
Overall Performance Metrics (SVM with Grid Search):
Accuracy: 0.7355021216407355
Precision: 0.7490463127414595
Recall: 0.7355021216407355
F1 Score: 0.723451689368978

Performance Metrics for Each Label (SVM with Grid Search):
                   precision    recall  f1-score   support

           Social       1.00      0.40      0.57         5
    Entertainment       0.78      0.61      0.69       100
     Productivity       0.59      0.50      0.54        60
  Developer Tools       1.00      0.33      0.50         9
  Personalization       1.00      0.90      0.95        51
Utilities & Tools       0.43      0.71      0.54        78
Multimedia Design       0.83      0.38      0.53        13
         Business       0.52      0.52      0.52        27
        Education       0.67      0.41      0.51        34
         Security       0.33      0.25      0.29         4
Books & Reference       0.75      0.19      0.30        16
       

In [30]:
import numpy as np

# Initialize confusion matrix array
num_classes = len(labels)
confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

# Map labels to indices
label_to_index = {label: index for index, label in enumerate(labels)}

# Iterate through predictions and labels to populate the confusion matrix
for pred, true_label in zip(y_pred_svm_grid, y_test):
    pred_index = label_to_index[pred]
    true_index = label_to_index[true_label]
    confusion_matrix[true_index, pred_index] += 1

# Print the confusion matrix array
print("Confusion Matrix of Classification:")
print(confusion_matrix)


Confusion Matrix of Classification:
[[  2   0   2   0   0   1   0   0   0   0   0   0   0   0   0]
 [  0  61   3   0   0  11   1   5   3   0   0   1   0  15   0]
 [  0   3  30   0   0  20   0   3   0   1   0   0   0   3   0]
 [  0   0   1   3   0   4   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0  46   4   0   0   0   0   0   0   0   1   0]
 [  0   8   9   0   0  55   0   1   2   0   0   0   0   3   0]
 [  0   3   1   0   0   2   5   0   0   0   0   0   0   2   0]
 [  0   0   3   0   0   9   0  14   0   0   0   0   0   1   0]
 [  0   0   0   0   0   8   0   0  14   1   1   0   0   9   1]
 [  0   0   1   0   0   2   0   0   0   1   0   0   0   0   0]
 [  0   1   1   0   0   8   0   1   0   0   3   0   0   2   0]
 [  0   1   0   0   0   2   0   1   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   8   0]
 [  0   1   0   0   0   1   0   1   1   0   0   0   1 282   2]
 [  0   0   0   0   0   0   0   0   1   0   0   0   0   3   1]]


In [ ]:
label_to_index

In [ ]:
###DL

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Convert category labels to numerical labels
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Convert numerical labels to categorical format
num_classes = len(label_encoder.classes_)
y_train_categorical = to_categorical(y_train_encoded, num_classes=num_classes)
y_test_categorical = to_categorical(y_test_encoded, num_classes=num_classes)


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [ ]:
# Maximum number of words in a sentence
max_length = 100

# Pad sequences to the maximum length
x_train_pad = pad_sequences(x_train_cv.toarray(), maxlen=max_length, padding='post')
x_test_pad = pad_sequences(x_test_cv.toarray(), maxlen=max_length, padding='post')

# Define the CNN model
model = Sequential()
model.add(Embedding(input_dim=len(vocab), output_dim=100, input_length=max_length))
model.add(Conv1D(128, 5, activation='relu'))
model.add(GlobalMaxPooling1D())
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train_pad, y_train_categorical, epochs=10, batch_size=64, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(x_test_pad, y_test_categorical)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)


In [ ]:
# Predict probabilities on the test data
y_pred_probs = model.predict(x_test_pad)

# Get the class with the highest probability for each sample
y_pred = np.argmax(y_pred_probs, axis=1)

# Convert test labels back to their original format
y_test_original = label_encoder.inverse_transform(y_test_encoded)
y_pred_original = label_encoder.inverse_transform(y_pred)

# Compute accuracy
accuracy = accuracy_score(y_test_original, y_pred_original)

# Compute precision, recall, and F1-score
precision = precision_score(y_test_original, y_pred_original, average='weighted')
recall = recall_score(y_test_original, y_pred_original, average='weighted')
f1 = f1_score(y_test_original, y_pred_original, average='weighted')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

# Generate classification report
report = classification_report(y_test_original, y_pred_original, labels=labels)
print("\nClassification Report:")
print(report)
